### ISSUE TITLE
HTTP 401 is incorrectly handled on Mac OS X & iOS.

### ISSUE THREAD

**Issue by deathbaba** [deathbaba/Alohalytics#45]
[NSURLConnection sendSynchronousRequest] incorrectly returns nil and fails with error -1012 NSURLErrorUserCancelledAuthentication

http://stackoverflow.com/questions/2188099/nshttpurlresponse-statuscode-is-returning-zero-when-it-should-be-401

**Comment by dkorolev** [comment]
@mzhurovich migrated our code to asynchronous, you may want to take a look.

https://github.com/c5t/Current/commit/26c5b13ca209faa09166911b5f4256284a4d6ae8
https://github.com/c5t/Current/blob/master/Blocks/HTTP/impl/apple_client.mm

**Comment by dkorolev** [comment]
@mzhurovich migrated our code to asynchronous, you may want to take a look.

https://github.com/c5t/Current/commit/eb55eadab288806a775b7bb8b3ec6afcbce21674
https://github.com/c5t/Current/blob/master/Blocks/HTTP/impl/apple_client.mm

**Comment by deathbaba** [comment]
Thanks. Looks like it has the same issue with async implementation, simply patched https://github.com/c5t/Current/blob/master/Blocks/HTTP/impl/apple_client.mm#L101 <https://github.com/c5t/Current/blob/master/Blocks/HTTP/impl/apple_client.mm#L101>

**Comment by mzhurovich** [comment]
@deathbaba yep, but AFAIR this patch could be implemented only using async requests.

**Comment by deathbaba** [comment]
I think this piece of code can be easily applied to sendSynchronousRequest implementation too.
```
 if (error.code == NSURLErrorUserCancelledAuthentication) {
            http_response_code = 401;
            request_succeeded = true;
}
```
